### ISSUE TITLE
Want to add hamburger icon to nav bar for mobile view 

### ISSUE THREAD

**Issue by Vishal-Parasram** [Vishal-Parasram/Portfolio#4]
Greetings,

If you're interested in contributing to my personal project on GitHub, I'd love to have your support. Currently, I'm adding a hamburger icon to my navigation bar, and your expertise can make a significant impact on the project's success. Please reach out to me if you're interested in collaborating.

Thank you,

**Comment by mihirsingh241** [comment]
i want to contribute

**Comment by Harshavardhana-B-S** [comment]
I will contribute. I am good at CSS. Check my github profiel.

**Comment by VISHALDINESH** [comment]
@mihirsingh241 comment first so you can contribute

**Comment by VISHALDINESH** [comment]
@Harshavardhana-B-S if he can't then you can contribute ok.

**Comment by SHAIK-MUNEERUDDIN** [comment]
hey I also want to contribute in this too..
